date_format: "%Y-%m-%d"
permalink: /:slug

title: 7 Wheels
email: markassa@gmail.com
description: >-
  Ramblings of a software nerd
baseurl: "/blag"
url: "https://cruncha-cruncha.github.io"
github_username: cruncha-cruncha


plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jemoji

pagination:
  enabled: true
  debug: false
  per_page: 20
  permalink: "/page/:num/"
  collection: 'posts'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  tags:
    layout: tags
    permalink: /tag/:tag/

author:
  name: Liam Marcassa
  url: https://cruncha-cruncha.github.io/blag/

