title: 7 Wheels
email: markassa@gmail.com
description: >-
  Ramblings of a software nerd
baseurl: "/blag"
url: "https://cruncha-cruncha.github.io"
github_username: cruncha-cruncha

date_format: "%Y-%m-%d"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  debug: false
  per_page: 20
  permalink: "/page/:num/"
  collection: 'posts'
  sort_field: 'date'
  sort_reverse: true

autopages:
  enabled: true
  categories:
    layout: category
    permalink: /category/:cat/
  slugify:
    mode: 'default'  # :cat is slugified. Modes: default, raw, pretty, ascii, latin
    case: true

author:
  name: Liam Marcassa
  url: https://cruncha-cruncha.github.io/blag/

