name: "Build and Deploy Blag"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  packages: read

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.CRUNCHA_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull Docker image
        run: docker pull ghcr.io/cruncha-cruncha/blag-compiler:latest
      - name: Build static files
        run: |
          mkdir -p built
          docker run --rm \
            -v "$PWD/site:/blag/site" \
            -v "$PWD/built:/blag/build" \
            -v "$PWD/compiler/blag_info.json:/blag_info.json" \
            -e REPO_NAME=${{ github.event.repository.name }} \
            ghcr.io/cruncha-cruncha/blag-compiler:latest
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: built/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4