name: "Build and Deploy Blag"

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build static files
        id: build
        run: |
          echo "Building Docker image..."
          docker build -t blag-compiler -f ./compiler/Dockerfile ./compiler
          echo "Making built directory..."
          mkdir -p built
          echo "Running Docker container..."
          docker run --rm \
            -v "$PWD/posts:/blag/posts" \
            -v "$PWD/built:/blag/build" \
            blag-compiler

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: built/

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4